[package]
name = "socketcan-alt"
version = "0.1.0"
authors = ["Toru Ogawa <Hakuyume@users.noreply.github.com>"]
edition = "2018"
description = "Rust binding for SocketCAN"
license = "BSD-3-Clause"
documentation = "https://docs.rs/crate/socketcan-alt/"
repository = "https://github.com/Hakuyume/socketcan-rs"
exclude = [".github"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test_all = []

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = { version = "0.52", default-features = false, features = ["runtime"] }

[dev-dependencies]
rand = "0.7"
spin = "0.5"
structopt = "0.3"
