[package]
name = "socketcan-alt"
version = "0.2.1"
authors = ["Toru Ogawa <Hakuyume@users.noreply.github.com>"]
edition = "2018"
description = "Rust binding for SocketCAN"
license = "BSD-3-Clause"
documentation = "https://docs.rs/crate/socketcan-alt/"
repository = "https://github.com/Hakuyume/socketcan-rs"
readme = "README.md"
exclude = [".github"]

[package.metadata.docs.rs]
all-features = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
aio = ["futures", "mio", "tokio"]

[dependencies]
bitflags = "1.2"
futures = { version = "0.3", optional = true }
libc = "0.2"
mio = { version = "0.6", optional = true }
tokio = { version = "0.2", features = ["io-driver"], optional = true }

[build-dependencies]
bindgen = { version = "0.52", default-features = false, features = ["runtime"] }

[dev-dependencies]
rand = "0.7"
spin = "0.5"
structopt = "0.3"
tokio = { version = "0.2", features = ["macros", "rt-core", "time"] }
