name: Rust

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cargo build --verbose --all-targets
    - run: cargo test --verbose
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cargo fmt --verbose -- --check
    - run: cargo clippy --all-targets
