name: Rust

on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
        - x86_64-unknown-linux-gnu
        - x86_64-unknown-linux-musl
        header:
        - v2020.11.0
        - v2020.12.0
        dependency-versions:
        - minimal
        - maximum
    env:
      BINDGEN_EXTRA_CLANG_ARGS: -Ican-utils/include
    steps:
    - uses: actions/checkout@v2
    - run: rustup update
    - if: matrix.dependency-versions == 'minimal'
      run: |
        rustup toolchain add nightly
        cargo +nightly update -Z minimal-versions
    - run: rustup target add ${{ matrix.target }}
    - run: git clone https://github.com/linux-can/can-utils.git --branch ${{ matrix.header }} --depth 1
    - run: >-
        cargo build --verbose
        --target ${{ matrix.target }}
        --all-targets
        --features aio
        $([ ${{ matrix.header }} = v2020.11.0 ] && echo --features can-dlc-unaliased)
    - run: >-
        cargo test --verbose
        --target ${{ matrix.target }}
        --features aio
        $([ ${{ matrix.header }} = v2020.11.0 ] && echo --features can-dlc-unaliased)
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup update
    - run: cargo fmt --verbose -- --check
    - run: cargo clippy --all-targets --features aio --features can-dlc-unaliased
