name: Rust

on:
  push:
    branches: [master]
  pull_request:

env:
  BINDGEN_EXTRA_CLANG_ARGS: -Ican-utils/include
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
        - x86_64-unknown-linux-gnu
        - x86_64-unknown-linux-musl
        dependency-versions:
        - minimal
        - maximum
    steps:
    - uses: actions/checkout@v2
    - run: git clone --depth 1 https://github.com/linux-can/can-utils.git
    - if: matrix.dependency-versions == 'minimal'
      run: |
        rustup toolchain add nightly
        cargo +nightly update -Z minimal-versions
    - run: rustup target add ${{ matrix.target }}
    - run: cargo build --verbose --target ${{ matrix.target }} --all-targets --all-features
    - run: cargo test --verbose --target ${{ matrix.target }} --all-features
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git clone --depth 1 https://github.com/linux-can/can-utils.git
    - run: cargo fmt --verbose -- --check
    - run: cargo clippy --all-targets --all-features
